version: "3.8"

services:
  java_app:
    container_name: "character-viewer-app"
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      PORT: 8080
      HEROKU_PORT: 8080
      NODE_ENV: 'development'
      DOMAIN_NAME: 'http://localhost'
    ports:
      - '8080:8080'
