version: "3.8"

services:
  java_app:
    container_name: "character-viewer-app"
    build:
      context: .
    environment:
      JAR_FILE: "./target/*.jar"
      PORT: 8080
      HEROKU_PORT: 8080
    ports:
      - 8080:8080
