spring:
  server:
    port: ${PORT:8080}
  application:
    name: CharacterViewerApp
# examples to add datasource for db uri
  datasource:
    url: jdbc:h2:mem:charviewer
    name: username
    password: password
