spring:
  server:
    port: ${PORT:8080}
  application:
    name: CharacterViewerApp
  # TODO settings for adjusting postgres dialect
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:h2:mem:charviewer
    name: username
    password: password
    # TODO Use for local database instance
    #url: jdbc:postgresql://localhost:5432/characters
    #name: charactersuser
    #password: password
    # TODO look into issues with loading into heroku postgres instance
    #url: jdbc:postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    #name: ${DB_USER}
    #password: ${DB_PASSWORD}
