name: Docker Image Build and Deployment

env:
  JAVA_VERSION: '17'
  DISTRIBUTION: zulu


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag build/characterviewerapp .

    # todo - add deploy key for setting up AWS ECS deployment
    # deploy: ...
